# This is a temporary file used to clean up dev/ before other directories
include: ../analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false # this directory only contains test code
